CREATE TABLE books (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(250),
  author_id MEDIUMINT NOT NULL, 
  PRIMARY KEY (id)
);

CREATE TABLE authors (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100),
  PRIMARY KEY (id)
);

CREATE TABLE customers (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100),
  PRIMARY KEY (id)
);

CREATE TABLE orders (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  customer_id MEDIUMINT NOT NULL,  
  PRIMARY KEY (id)
);

CREATE TABLE order_line_items (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  order_id MEDIUMINT NOT NULL,
  book_id MEDIUMINT NOT NULL,
  quantity SMALLINT NOT NULL,
  PRIMARY KEY (id)
);